name: Node.js CI

on:
  push:
    branches:
      
      - main

jobs:
  build:

    runs-on: ubuntu-latest

  stall dependencies
      run: npm install

    - name: Start application
      run: npm start
